CREATE TABLE IF NOT EXISTS [settings](
	[id] INTEGER PRIMARY KEY  AUTOINCREMENT NOT NULL, 
	[key] NVARCHAR2(100) NOT NULL UNIQUE, 
	[value] nvarchar2(500));

INSERT INTO settings (key, value) VALUES ('admin', 'ef51306214d9a6361ee1d5b452e6d2bb70dc7ebb85bf9e02c3d4747fb57d6bec');

CREATE TABLE IF NOT EXISTS  [users](
	[id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	[port] INTEGER NOT NULL UNIQUE, 
	[password] NVARCHAR2(64) NOT NULL, 
	[traffic_limit] INTEGER NOT NULL DEFAULT 0, 
	[traffic_left] INTEGER NOT NULL DEFAULT 0, 
	[expiration_date] DATE NOT NULL, 
	[created_date] DATE NOT NULL DEFAULT (DATE ('now')));


CREATE TABLE IF NOT EXISTS [traffics](
	[id] INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL, 
	[port] INTEGER NOT NULL, 
	[log_date] DATETIME NOT NULL, 
	[amount] INTEGER NOT NULL DEFAULT 0);
